language: java
jdk:
 - oraclejdk8
script: mvn clean install --batch-mode
matrix:
    - jdk: oraclejdk8
branches:
  only:
    - 2.0.x
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
sudo: false
