#
#  This Source Code Form is subject to the terms of the Mozilla Public License,
#  v. 2.0. If a copy of the MPL was not distributed with this file, You can
#  obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
#  the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
#
#  Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
#  graphic logo is a trademark of OpenMRS Inc.
#
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: warn

common:
  path_prefix: /loki/data
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
        
storage_config:
    filesystem:
        directory: /loki/data/chunks

compactor:
  working_directory: /loki/data/compactor
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  retention_period: 336h # 14 days
  
  # Rate limits
  ingestion_rate_strategy: global
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  
  # Stream limits
  max_global_streams_per_user: 10000
  max_streams_per_user: 0
  
  # Validation
  max_line_size: 256KB
  max_line_size_truncate: false
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 15
  
  # Time constraints
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  creation_grace_period: 10m
  unordered_writes: true

ingester:
  # Chunk settings
  chunk_idle_period: 30m
  chunk_target_size: 1572864  # 1.5 MB
  chunk_encoding: snappy
  max_chunk_age: 2h
  
  # WAL settings
  wal:
      enabled: true
      dir: /loki/data/wal
      checkpoint_duration: 5m
      flush_on_shutdown: true
