name: "üîéCAST Highlight Code Scan - Demo NBI"

description: Run CAST Highlight scans on your code to get Software Intelligence insights (vulnerabilities, cloud maturity, etc.)

on: # action triggers, here every two weeks (days 5 and 15 of the month) at 6am
  workflow_dispatch:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    # use the prod environment, where the secret CAST_HIGHLIGHT_API_TOKEN is defined
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: "üè≠Get company and application ids"
        run: |
          if [ -f .github/workflows/Highlight.env ]; then
            cat .github/workflows/Highlight.env >> $GITHUB_ENV
          else
            echo "Highlight.env file not found!"
            exit 1
          fi

      - name: "‚õèÔ∏èScan repository source code with CAST Highlight Code Reader" 
        run: |
          docker run --rm -v $(pwd):/s -v /tmp:/w  casthighlight/cli \
                                                   --sourceDir /s \
                                                   --workingDir /w \
                                                   --tokenAuth ${{ secrets.CAST_HIGHLIGHT_API_TOKEN }} \
                                                   --companyId ${{ env.companyId }} \
                                                   --applicationId ${{ env.applicationId }} \
                                                   --serverUrl ${{ env.serverUrl }} \
                                                   --ignoreDirectories ${{ env.ignoreDirectories }} \
                                                   --technologies ${{ env.technologies }}
