name: "OWASP Dependency Check"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  dependencycheck:
    runs-on: ubuntu-latest
    name: dependencycheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Java version
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn clean install -DskipTests
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'openmrs-core'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 6.2
            --enableRetired
            --suppression dependency-check-suppressions.xml
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
           name: Dependency Check report
           path: ${{github.workspace}}/reports
